name: provision Terraform

on:
  workflow_dispatch:  # Manually triggered only (avoid auto apply on push)

jobs:
  bootstrap:
    name: Run Terraform infrastructure provisioning
    runs-on: ubuntu-latest

    environment: Test  # Optional: Use protected env for approvals

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan     
        run: terraform plan

      - name: Terraform Apply (auto-approve)
        run: terraform apply -auto-approve
